### ISSUE TITLE
different font weights or colors for only some words in add_subtitle

### ISSUE THREAD

**Issue by werkstattcodes** [kcuilla/reactablefmtr#12]
Many thanks for this powerful package. 

Is there any way to highlight only some words (e.g. bold, different color) when using `add_subtitle`.
It tried `add_subtitle(subtitle="text text <span style='color:red;'>text to highlight</span> text text")` but without luck. Any idea?

Many thanks again.

**Comment by kcuilla** [comment]
Thank you for this suggestion. I've added the `html()` helper function to allow this to work as shown below. It should work within `add_title()` and `add_source()` as well.

<br>

`data <- iris[10:29, ]`
`reactable(data) %>% 
add_subtitle(subtitle=html("text text <span style='color:red;'>text to highlight</span> text text"))`

![image](https://user-images.githubusercontent.com/17436783/133870384-98ddd9f9-d5da-46e6-bef9-b8ad8cb5e8d6.png)
