### ISSUE TITLE
icon_assign for the column with NA values output "NA" text in a given cell

### ISSUE THREAD

**Issue by bbt-dev** [kcuilla/reactablefmtr#15]
First of all, thanks a lot for the development of reactablefmtr package!

When I produce a reactable table and use icon_assign for column which contains NA values, it produces output "NA" in a given cell. I tried to look at the [documentation](https://kcuilla.github.io/reactablefmtr/reference/icon_assign.html) but didn't find any parameter that would regulate this behaviour. I tried to experiment with some !is.na(data) inside the icon_assign, or ifelse(!is.na(data), cell = icon_assign(data, icon = "user")) - but without success.
Please could you let me know how it is possible to suppress "NA" output for the cells reflecting NA values?

Here is a RE:
```
data <- MASS::Cars93[1:20, c("Make", "Passengers")]
data[2, 2] <- NA

reactable(
  data,
  defaultColDef = colDef(maxWidth = 300, align = "center", na = "",
                         cell = icon_assign(data, icon = "user")
  )
)
```

**Comment by mrworthington** [comment]
Hey Kyle! Is there a way to extend this functionality to `data_bars()` as well? Right now, NA's populate and using `na = ""` under `colDef()` doesn't do anything to address the issue.

**Comment by kcuilla** [comment]
Hey Matt, thanks for pointing this out. I just added this functionality to `data_bars()` in the dev version.  Here's an example below:

```r
# install dev version
remotes::install_github("kcuilla/reactablefmtr")
library(reactablefmtr)

data <- MASS::Cars93[1:20, c("Make", "Passengers")]
data[2, 2] <- NA

reactable(
  data,
  defaultColDef = colDef(maxWidth = 300, align = "center",
                         cell = data_bars_test(data)
  )
)
```

![image](https://user-images.githubusercontent.com/17436783/195872870-ee01e1a9-e91d-4443-b331-1efc806abc24.png)

**Comment by pieterprovoost** [comment]
@kcuilla This is not working for me using the dev version.
