### ISSUE TITLE
Sparklines: some [value] labels are hidden under top headline

### ISSUE THREAD

**Issue by sfd99** [kcuilla/reactablefmtr#17]
**Great PKG!!!**.

**Problem:**
as you hover the mouse along some sparklines examples
in page:
https://kcuilla.github.io/reactablefmtr/articles/sparklines.html

...some MAX [value] labels become hidden 
under the top headline:
"Species .... Sex..... Flipper_length"

At that point, you can not read the value...

**EX:**
https://kcuilla.github.io/reactablefmtr/articles/sparklines.html#htmlwidget-47f673e7c71ff2e55859

This "hidden value label" effect,
(as you move your mouse over the Sparkline),
happens on several examples in the Examples page.
Page Zooming in/out, does not help.

_Try it!._
**SFd99
San Francisco
Chrome / Chromium Version 95.0.4638.69 (Official Build)
Ubuntu LINUX 20.04**

**Comment by sfd99** [comment]
Kyle, anybody -
could somebody please help?...

I tried again today,  
March 10 2022
and still have exactly the same problem
as described in my 1st post (above).

Tried with the latest versions
of Chrome, Firefox and  Brave browsers.

Same problem...
as you hover the mouse over any sparkline,
the [value label] that pops up
is partially hidden 
behind any sparkline above...
So, you can not clearly read the label value.

**EX:**
https://kcuilla.github.io/reactablefmtr/articles/sparklines.html#htmlwidget-47f673e7c71ff2e55859

This "hidden value label" effect,
(as you move your mouse over the Sparkline),
happens on several examples in the Examples page.
Page Zooming in/out, does not help.

Try it!. 
Thanks for any pointers,
Kyle, anybody?....

SFd99
San Francisco
Chrome / Chromium Version  99.0.4844.51 (Official Build)
+also tried w/ latest Firefox and Brave browsers.
(so, it's not browser-related...)
Ubuntu LINUX 20.04
================

**Comment by kcuilla** [comment]
Hi, sorry for the late response on this. I'm working on expanding the tooltip options and fixing this. Hoping to have an updated version of the sparklines pushed to GH tomorrow.

**Comment by sfd99** [comment]
Thanks for responding, Kyle!.
Looking forward to the fix...

I was going bananas 
trying to figure out 
what I was doing wrong.... :-)

**Comment by kcuilla** [comment]
No problem, sorry for all the investigative work on your part. I've updated the tooltips in the sparklines and added more options such as the ability to change the size, color, and type of tooltip. Please see the updated sparklines tutorial for examples: https://kcuilla.github.io/reactablefmtr/articles/sparklines.html#tooltip-options

**Comment by sfd99** [comment]
_**Kyle -**_

Works super-great now!
Thanks!!!.

There is still **ONE particular value** 
partially visible, (hidden)
on mouse hover,
in the example sets of that webpage.

Try to hover your mouse 
over the leftmost (first) point 
of the **Gentoo / Male** sparkline, 
(last sparkline of any sparkline set)

See?.
The value: 
   "230" 
is only partially visible.
All the other on-hover values are "fully visible".

So, the "hidden value" effect,
could also happen with sparklines
of other _new_ data sets ...

Hey! - Worth looking at. :-)

Thanks, Kyle!.
**SFd99
Latest RSTUDIO.
Ubuntu LINUX 20.04
reactablefmtr PKG 2.0.0 (latest) PKG 
dataui PKG 0.0.1 (latest)
Chrome / Chromium Version 99.0.4844.51 (Official Build)**

**Comment by kcuilla** [comment]
Thanks for pointing those out to me. NOW it should be fixed and all values visible in the tutorial https://kcuilla.github.io/reactablefmtr/articles/sparklines.html#tooltip-options

There may be certain datasets where not all of the values will be completely visible in the tooltip using the default settings, but the user will be able to adjust the height and margins of the sparklines as well as the size of the tooltip labels as well.

**Comment by sfd99** [comment]
Wow, Kyle.
_Really_ impressive now...

Thanks
and have a great weekend!.

**SFd99
Latest RSTUDIO.
Ubuntu LINUX 20.04
reactablefmtr PKG 2.0.0 (latest) PKG
dataui PKG 0.0.1 (latest)
Chrome / Chromium Version 99.0.4844.51 (Official Build)**
