### ISSUE TITLE
Consider using scales package?

### ISSUE THREAD

**Issue by hadley** [kcuilla/reactablefmtr#2]
This would allow you to pretty easily support many of the same scales that ggplot2 does. Happy to provide some pointers if it would help.

**Comment by kcuilla** [comment]
That's a great suggestion, thank you! I added it to the icon_sets() function and it's working perfectly. 

However, I tested it out in data_bars() and was having issues with the alignment of numbers of different lengths. The current method involves taking the max number of characters in a column and setting that as the width in base format. Is there an equivalent to the width argument in scales?

    max_digits <- nchar(max(data[[name]]))

    value <- format(value,
                    width = max_digits,
                    justify = "right")

<b>data_bars() currently:</b>
![image](https://user-images.githubusercontent.com/17436783/108774651-ec196f00-752d-11eb-95a4-ff87c7fe27ef.png)


<b>data_bars() with scales::dollar_format applied:</b>
![image](https://user-images.githubusercontent.com/17436783/108774457-b1afd200-752d-11eb-8ebe-9674c51c07a0.png)

**Comment by hadley** [comment]
You could just left pad the generated strings?

``` r
x <- c(7.4, 8, 10, 100)
x <- scales::dollar_format()(x)
stringr::str_pad(x, max(nchar(x)))
#> [1] "  $7.40" "  $8.00" " $10.00" "$100.00"
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by kcuilla** [comment]
That worked! Thank you so much for your help

![image](https://user-images.githubusercontent.com/17436783/108850953-eb2a2100-75b1-11eb-93da-d0fe0c4e4b42.png)
