### ISSUE TITLE
data_bars error if NA is in the column data

### ISSUE THREAD

**Issue by milesmania** [kcuilla/reactablefmtr#21]
Thanks very much for this excellent r package.  The following error occurs when adding data_bars to a column definition with data containing an NA.

**Error in if (stats::var(data[[name]]) == 0) { : 
  missing value where TRUE/FALSE needed**

**Example code:**
```
data <- data.frame(
  Group = c("Red Group 1","Red Group 2","Red Group 3","Red Group 4","Red Group 5",
            "Blue Group 1","Blue Group 2","Blue Group 3","Blue Group 4","Blue Group 5",
            "Green Group 1","Green Group 2","Green Group 3","Green Group 4","Green Group 5"),
  Pct1 = c(.27, .82, .44, .68, .78, 
           .74, .66, .33, .23, .20, 
           .50, .55, .40, .70, .60),
  Pct2 = c(.33, .17, .87, .54, .37,
           .84, .72, .61, .48, .77,
           .21, .39, .60, .55, .81)
)

reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     number_fmt = scales::percent)
  )
)
```

Could this be fixed by adding an **na.rm=TRUE** to the if statement just like in the min/max formulas with the else clause of the same if statement:

if (stats::var(data[[name]]) == 0, **na.rm=TRUE**) {
      normalized <- 1
    }
    else {
      normalized <- (value - min(data[[name]], na.rm = TRUE))/(max(data[[name]], 
        na.rm = TRUE) - min(data[[name]], na.rm = TRUE))
    }

I'd prefer to show a blank cell for NA data in a data_bars column similar to other colDef types.

Thanks again!

**Comment by milesmania** [comment]
Oops I just saw this same error is fixed in the pull requests.  Sorry! #18

**Comment by milesmania** [comment]
On second look I think this is a different issue with the same function.

**Comment by milesmania** [comment]
Here's the code snippet for a reproducible example:
  
  ```
data <- data.frame(
    Group = c("Test NA","Red Group 1","Red Group 2","Red Group 3"),
    Pct1 = c(NA,.27, .82, .44),
    Pct2 = c(NA,.33, .17, .87)
  )
  
  reactable(
    data,
    pagination = FALSE,
    defaultColDef = colDef(
      cell = data_bars(data, 
                       number_fmt = scales::percent)
    )
  )
```

**Comment by kcuilla** [comment]
Hi Miles,

Please try installing the latest dev version with `remotes::install_github("kcuilla/reactablefmtr")`

I recently pushed an update that should fix this and display the NA's but let me know if you are still seeing the issue.

Thanks,
Kyle

**Comment by milesmania** [comment]
Thanks, Kyle.

That fixed my issue, much appreciated!

Cheers,
Ryan
