### ISSUE TITLE
Cannot install developers version from github

### ISSUE THREAD

**Issue by sotirismargaritis** [kcuilla/reactablefmtr#23]
Hello,

I use this code remotes::install_github("kcuilla/reactablefmtr") and installed dataui package too and i get this message: 
Why is this happening??

* installing *source* package 'reactablefmtr' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'reactable' was built under R version 4.0.5
Execution halted
ERROR: lazy loading failed for package 'reactablefmtr'
* removing 'F:/R/R-4.0.3patched/library/reactablefmtr'
Error: Failed to install 'reactablefmtr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/swtos/AppData/Local/Temp/Rtmp2Bddud/file1c14231638/reactablefmtr_1.1.0.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by kcuilla** [comment]
Hi what version of R are you using?

**Comment by sotirismargaritis** [comment]
Hello,

I think its 4.0.3

**Comment by kcuilla** [comment]
It looks like the error is due to the reactable package was built with a newer version of R than what you're currently using. I would try installing reactable on it's own with `install.packages("reactable")` and then try `remotes::install_github("kcuilla/reactablefmtr")`. If you're still getting an error message, you may need to update your version of R to 4.0.5.

**Comment by kcuilla** [comment]
I just realized you mentioned that you cannot use the react_sparkline function. In order to use the sparklines, you will need to download the {dataui} package from GitHub separately (it's currently not on CRAN). You can download it with: `remotes::install_github("timelyportfolio/dataui")`

**Comment by kcuilla** [comment]
The latest version of reactablefmtr (2.0.0) is now on CRAN so no need to download the developers version for whatever you need it for
