### ISSUE TITLE
Row-wise formatting?

### ISSUE THREAD

**Issue by justlebeau** [kcuilla/reactablefmtr#3]
Can color_scales be applied row-wise?  Similar to "area" in formattable?

**Comment by kcuilla** [comment]
Thanks for the suggestion, I just updated color_scales and color_tiles to allow for row-wise formatting by setting `span = TRUE`. Example shown here: https://kcuilla.github.io/reactablefmtr/articles/color_scales.html#using-span-1

**Comment by justlebeau** [comment]
Thank you...can the formatting be limited to a row or multiple non-adjacent rows but not all rows?  For example:  color_scales(data[2:6,],span=TRUE)

This is a much needed package...thank you for your efforts!

-Justin

**Comment by kcuilla** [comment]
Just added the ability to apply span to particular columns thanks to help from June. Most likely for the next CRAN release I won't have the row sub-setting available, but it may be something I re-visit at a future date.
