### ISSUE TITLE
Color scale borders

### ISSUE THREAD

**Issue by RedEric** [kcuilla/reactablefmtr#39]
Hi

Just have to say again this is a great package!

Was just wondering - when using color_scale to build a heat map is it possible to apply slight borders to differentiate each tile similar to the effect you would get when adding a border to geom_tile in a ggplot heat map?

Thanks

Michael

**Comment by kcuilla** [comment]
Thank you! I think this is a great idea. I will share a few examples once it's been added to the code

**Comment by kcuilla** [comment]
Hi Michael,

I just added the option to add borders to both `color_scales()` and `color_tiles()` within the dev version.

You can control the appearance of the borders with three options: `border_color`, `border_style`, and `border_width`.

```r
library(reactablefmtr)

reactable(
  iris[10:19,],
  defaultColDef = colDef(
    style =  color_scales(
      data = iris[10:19,],
      show_text = FALSE,
      border_color = 'grey')
  )
)
```
![image](https://user-images.githubusercontent.com/17436783/187041194-20de8e0a-640a-42eb-9137-22bbea52c048.png)

```r
reactable(
  iris[10:19,],
  defaultColDef = colDef(
    style =  color_scales(
      data = iris[10:19,],
      show_text = FALSE,
      border_color = 'black',
      border_style = 'dashed',
      border_width = 'thin')
  )
)
```
![image](https://user-images.githubusercontent.com/17436783/187041324-12ee7b05-c754-41e9-8d8f-934156821172.png)

**Comment by RedEric** [comment]
Thank you so much for this - really cool feature to have!
