### ISSUE TITLE
Change name of column

### ISSUE THREAD

**Issue by benjaminwnelson** [kcuilla/reactablefmtr#5]
Great package! Is there a way to relabel columns?

**Comment by kcuilla** [comment]
Column names can be re-labeled by specifying name within reactable::colDef.

data <- MASS::Cars93[20:49, c("Make", "MPG.city", "MPG.highway")]

reactable(
  data,
  columns = list(
    MPG.city = colDef(name = "MPG (city)"),
    MPG.highway = colDef(name = "MPG (highway)")))

![image](https://user-images.githubusercontent.com/17436783/112851233-c88b9c00-9078-11eb-85a4-d516a303fa08.png)

More examples shown here: https://glin.github.io/reactable/articles/examples.html#column-definitions-1

**Comment by benjaminwnelson** [comment]
Thank you!
