### ISSUE TITLE
Example with data_bars not working

### ISSUE THREAD

**Issue by werkstattcodes** [kcuilla/reactablefmtr#50]
Fyi - The example from the package's site [here ](https://kcuilla.github.io/reactablefmtr/articles/data_bars.html#:~:text=You%20are%20still%20able%20to%20control%20the%20position%20of%20the%20text%20relative%20to%20the%20bars%20with%20text_position%3A)isn't working. The bars/text are not visible.

``` r
library(tidyverse)
library(reactable)
library(reactablefmtr)
#> 
#> Attaching package: 'reactablefmtr'
#> The following object is masked from 'package:ggplot2':
#> 
#>     margin

car_data <- MASS::Cars93 %>% 
  filter(Type %in% c('Compact', 'Sporty', 'Van')) %>% 
  select(c('Make', 'Type', 'MPG.city')) %>% 
  mutate(Make = as.character(Make)) %>% 
  tail(10)

reactable(
  car_data,
  defaultSorted = "MPG.city",
  defaultSortOrder = "desc",
  columns = list(
    Make = colDef(
      cell = data_bars(car_data, fill_by = "MPG.city", text_position = "above")
    )
  )
)
```

![](https://i.imgur.com/sxpxeYl.png)

``` r

packageVersion("reactable")
#> [1] '0.4.1'
packageVersion("reactablefmtr")
#> [1] '2.1.0'
```

<sup>Created on 2022-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kcuilla** [comment]
Thanks for bringing this to my attention. It looks like it was inadvertently caused by the last update I had made to `data_bars()`. I just fixed it and it should be working now in the latest dev version.
