### ISSUE TITLE
Is it possible to save table as a pdf or svg file ?

### ISSUE THREAD

**Issue by sajjadasaf** [kcuilla/reactablefmtr#6]
First of all thank you very much for such a nice package. Its really great. I have few quires regarding the saving format. Is it possible to save it as an image like svg format? Can we change the column width according to our own choice? How to get publication ready images?

Thank you

**Comment by kcuilla** [comment]
Thank you for your comment and suggestion! There currently isn't a streamlined way of doing this yet, but I think this would be a great addition! I will work on it and see if I can add this capability

**Comment by kcuilla** [comment]
I have added the ability to save a reactable table as a static png file or dynamic html file with `save_reactable()`. 

Here's an example showing how. Also, you can set the column widths with maxWidth within colDef like I did below (can also use minWidth as well):

`data <- data.frame(
  Group = c("Group 1","Group 2","Group 3","Group 4","Group 5",
            "Group 6","Group 7","Group 8","Group 9","Group 10"),
  Value = c(27, 82, 44, 68, 78, 
            74, 66, 33, 23, 11)
)

example_table <- reactable(data,
                           columns = list(
                             Group = colDef(maxWidth = 100),
                             Value = colDef(maxWidth = 400,
                                            align = "left",
                                          cell = data_bars(
                                            data,
                                            fill_color = "lightgrey",
                                            text_position = "inside-end"))
                           ))

save_reactable(example_table, "example_table.png")`

![example_table](https://user-images.githubusercontent.com/17436783/115922571-12cf2580-a44b-11eb-82b0-7caa3e85e55a.png)

**Comment by sajjadasaf** [comment]
Thank you very for adding such a nice feature.
