### ISSUE TITLE
Data bars / color scales with aggregated data using groupBy

### ISSUE THREAD

**Issue by domsle** [kcuilla/reactablefmtr#8]
Hello,

When creating a reactable with an argument `groupBy` set to a specific column, and defining a aggregate function for another column, the aggregated level will not have any data bars rendered. 

I couldn't find any relevant info in the documentation. It this something that could be solved?

I guess that a quick workaround is to create an embedded sub-table using expanded rows, but this is not a perfect solution.

**Comment by kcuilla** [comment]
Hi,

Do you have any code you can show me? I just tried using the example below and it's working for both data_bars and color_scales: 

``` 
library(reactablefmtr)

data <- MASS::Cars93[4:8, c("Type", "Price", "MPG.city", "DriveTrain", "Man.trans.avail")]

reactable(
  data,
  groupBy = "Type",
  columns = list(
    Price = colDef(aggregate = "max", cell = data_bars(data)),
    MPG.city = colDef(aggregate = "mean", style = color_scales(data), format = colFormat(digits = 1)),
    DriveTrain = colDef(aggregate = "unique"),
    Man.trans.avail = colDef(aggregate = "frequency")
  ),
  rowStyle = JS("function(rowInfo) {
    if (rowInfo.level > 0) {
      return { background: '#eee', borderLeft: '2px solid #ffa62d' }
    } else {
      return { borderLeft: '2px solid transparent' }
    }
  }"),
  defaultExpanded = TRUE
)
```

![image](https://user-images.githubusercontent.com/17436783/122783696-c99b2680-d27f-11eb-9ea5-24fb1aa16f54.png)

**Comment by kcuilla** [comment]
Ah nevermind I just re-read what you said and know what you mean now...you want it to show on the aggregate level in addition to the detailed level. I haven't looked at that before so will need to check to see if that can be done!

**Comment by domsle** [comment]
Please forgive me for not providing a reprex, but I just have thought that my question is clear without the code. 

Thank you in advance for looking into this :)

**Comment by thohan88** [comment]
Faced the exact same issue today. I found this [issue](https://github.com/glin/reactable/issues/59) helpful.

**Comment by kcuilla** [comment]
I was able to look into this and there isn't a way to easily implement it to work with `groupBy`. 

However, there is still a way that it can be done by 1) creating a dataset containing the aggregated levels 2) putting it into a reactable table 3) putting another reactable table inside the row details of that reactable table. This will allow the formatters to be displayed on both the aggregated and detailed level as shown in the example below:  

```
library(reactablefmtr)
library(dplyr)

data <- MASS::Cars93[4:8, c("Type", "Price", "MPG.city")]

data_avg <- data %>%
  group_by(Type) %>%
  summarize(Price = mean(Price),
            MPG.city = mean(MPG.city))

reactable(
  data_avg,
  columns = list(
    Price = colDef(cell = data_bars(data)),
    MPG.city = colDef(style = color_scales(data), format = colFormat(digits = 1))  
    ),
  details = function(index) {
    data_sub <- data[data$Type == data_avg$Type[index], ]
    reactable(data_sub,
             columns = list(
               Price = colDef(aggregate = "max", cell = data_bars(data)),
               MPG.city = colDef(aggregate = "mean", style = color_scales(data), format = colFormat(digits = 1))  
             )
    ) 
  }
)
```

![reactable_agg](https://user-images.githubusercontent.com/17436783/127792366-29c0181e-a1e3-4b1c-a059-64acda9b6162.JPG)
