### ISSUE TITLE
Center icon using icon_assign

### ISSUE THREAD

**Issue by andreweath** [kcuilla/reactablefmtr#9]
Is it possible to center icons within a column using icon_assign? I can achieve something similar with icon_position("above") using icon_sets, but all icons automatically align to the left with icon_assign. Thanks.

**Comment by kcuilla** [comment]
Hi, thank you for using {reactablefmtr}! I just added the ability to adjust the alignment of the icons within icon_assign() by using align_icons. In your case, you would just need to include `align_icons = "center"` to center the icons within a column.
